[package]
name = "entropy-base"
version = "0.2.2"
edition = "2021"
description = "entropy-game shared library"
license = "GPL-3.0"

[lib]

[dependencies]
bytes = "1.6.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.203", features = ["derive"] }
